name: Update GitHub Snake

on:
  schedule:
    - cron: "0 */6 * * *"   # Executa a cada 6 horas
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Gera as imagens da cobrinha
      - name: Generate Snake SVG (dark mode)
        uses: Platane/snk@v3
        with:
          github_user_name: paulohassad         # seu usuário
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_dots=#1a1a1a

      # 3️⃣ Copia as imagens para a pasta assets
      - name: Copy SVGs to assets
        run: |
          mkdir -p assets
          cp dist/github-snake.svg assets/github-snake.svg
          cp dist/github-snake-dark.svg assets/github-snake-dark.svg

      # 4️⃣ Commit e push das imagens atualizadas
      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets/github-snake.svg assets/github-snake-dark.svg
          git commit -m "Update GitHub snake animation" || echo "No changes to commit"
          git push
